# Site
repository: hhaaaaa/hhaaaaa.github.io
favicon: https://github.githubassets.com/favicons/favicon-dark.png

# Content configuration version
version: 2

# Personal info
name: í•˜  í˜„
title: Front-End Developer
email_title: Email
email: gkgusgkgus@naver.com
website_title: GitHub
website: https://github.com/hhaaaaa
phone_title: Phone
phone: 010-6860-5012

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
# github_username: hhaaaaa
# tistory_username: minemanemo
# rocketpunch_username: minhoe1122
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: minoi1122
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://drive.google.com/uc?id=19auG9OckT8OPs3mUj71tRSqYQX7nYHe_
about_content: |
  ê³„ì†í•´ì„œ ì„±ì¥í•˜ê³  ì‹¶ì€ í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì í•˜í˜„ì…ë‹ˆë‹¤.<br />
  ë¸”ë¼ë¸”ë¼

  <hr />

  `ë„ì „ ë¶€ì¡±ì±„ì›Œ` <br />
  í•™ë¶€, êµ­ë¹„, ì¸í„´

  `í•™ìŠµ ë°œì „` <br />
  ë¦¬ì•¡íŠ¸, í›…ìŠ¤, ìƒíƒœê´€ë¦¬

  `í”„ë¡ íŠ¸ ì¬ë°Œì–´` <br />
  ìœ¡ì•„ì˜ì‹ , ì‚¬ìš©ì ë§ì•„ì§, í”¼ë“œë°±ìœ ì§€ë³´ìˆ˜

  `í¬ë¶€` <br />
  ê³„íš, í¬ë¶€

  <hr />

  ì£¼ìš” ê´€ì‹¬ íŒŒíŠ¸ : <mark>WEB</mark> , <mark>Front-End</mark>

content:
  - title: Skill
    layout: text
    content: |
      <div style="max-width: 1000px; margin: 0 auto;">
        <div style="text-align: center;margin-bottom: 20px;min-width: 350px;font-size:1.4rem;font-style: italic;">
          ì—…ë¬´ í˜¹ì€ í”„ë¡œì íŠ¸ ê²½í—˜ì— ì‚¬ìš©í–ˆë˜ ê¸°ìˆ  í˜¹ì€ ë„êµ¬ë“¤ì…ë‹ˆë‹¤.<br />
        </div>
        
        <div style="margin: 0 auto;">
          <table>
            <tr>
              <td style="border: none; width: 30%; vertical-align: top; padding-left: 15px;">
                <p style="text-align: left;font-weight: bold;">ğŸ’» Front-End ğŸ’»</p>
              </td>
              <td style="border: none; width: 70%;">
                <div style="display: inline-block;text-align: left;margin-bottom: 20px;min-width: 350px;">
                  <img src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"/>
                  <img src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"/>
                  <img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=black"/>
                  <img src="https://img.shields.io/badge/jQuery-0769AD?style=flat-square&logo=jQuery&logoColor=white"/>
                  <br /><br />
                  <img src="https://img.shields.io/badge/React-61DAFB?style=flat-square&logo=React&logoColor=black"/>
                  <img src="https://img.shields.io/badge/React%20Router-CA4245?style=flat-square&logo=React-Router&logoColor=white"/>
                  <img src="https://img.shields.io/badge/styled%20components-DB7093?style=flat-square&logo=styled-components&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Material%20UI-0081CB?style=flat-square&logo=Material-UI&logoColor=white"/>
                  <br /><br />
                  <img src="https://img.shields.io/badge/ESLint-4B32C3?style=flat-square&logo=ESLint&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Prettier-F7B93E?style=flat-square&logo=Prettier&logoColor=white"/>
                  <img src="https://img.shields.io/badge/npm-CB3837?style=flat-square&logo=npm&logoColor=white"/>
                </div>
              </td>
            </tr>
          </table>
        </div><br/>

        <div style="margin: 0 auto;">
          <table>
            <tr>
              <td style="border: none; width: 30%; vertical-align: top; padding-left: 15px;">
                <p style="text-align: left;font-weight: bold;">ğŸ”‘ Back-End ğŸ”‘</p>
              </td>
              <td style="border: none; width: 70%;">
                <div style="display: inline-block;text-align: left;margin-bottom: 20px;min-width: 350px;">
                  <img src="https://img.shields.io/badge/Node.js-339933?style=flat-square&logo=Node.js&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Express-000000?style=flat-square&logo=Express&logoColor=white"/>
                  <img src="https://img.shields.io/badge/NGINX-009639?style=flat-square&logo=nginx&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Amazon%20AWS-232F3E?style=flat-square&logo=Amazon%20AWS&logoColor=white"/>
                  <br /><br />
                  <img src="https://img.shields.io/badge/MySQL-4479A1?style=flat-square&logo=MySQL&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Oracle-F80000?style=flat-square&logo=Oracle&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Apache2-D22128?style=flat-square&logo=Apache&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Swagger-85EA2D?style=flat-square&logo=Swagger&logoColor=white"/>
                  <br /><br />
                  <img src="https://img.shields.io/badge/Java-007396?style=flat-square&logo=Java&logoColor=white"/>
                  <img src="https://img.shields.io/badge/JSP-333333?style=flat-square&logo=JSP&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Spring-6DB33F?style=flat-square&logo=Spring&logoColor=white"/>
                  <img src="https://img.shields.io/badge/MyBatis-333333?style=flat-square&logo=MyBatis&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Maven-C71A36?style=flat-square&logo=Apache%20Maven&logoColor=white"/>
                </div>
              </td>
            </tr>
          </table>
        </div><br/>

        <div style="margin: 0 auto;">
          <table>
            <tr>
              <td style="border: none; width: 30%; vertical-align: top; padding-left: 15px;">
                <p style="text-align: left;font-weight: bold;">ğŸ›  Tools ğŸ› </p>
              </td>
              <td style="border: none; width: 70%;">
                <div style="display: inline-block;text-align: left;margin-bottom: 20px;min-width: 350px;">
                  <img src="https://img.shields.io/badge/Visual%20Studio%20Code-007ACC?style=flat-square&logo=Visual%20Studio%20Code&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Eclipse-2C2255?style=flat-square&logo=Eclipse%20IDE&logoColor=white"/>
                </div>
              </td>
            </tr>
          </table>
        </div><br/>

        <div style="margin: 0 auto;">
          <table>
            <tr>
              <td style="border: none; width: 30%; vertical-align: top; padding-left: 15px;">
                <p style="text-align: left;font-weight: bold;">âš™ï¸ Etc âš™ï¸</p>
              </td>
              <td style="border: none; width: 70%;">
                <div style="display: inline-block;text-align: left;margin-bottom: 20px;min-width: 350px;">
                  <img src="https://img.shields.io/badge/Git-F05032?style=flat-square&logo=Git&logoColor=white"/>
                  <img src="https://img.shields.io/badge/C-A8B9CC?style=flat-square&logo=C&logoColor=white"/>
                  <img src="https://img.shields.io/badge/C++-00599C?style=flat-square&logo=C++&logoColor=white"/>
                  <img src="https://img.shields.io/badge/Python-3776AB?style=flat-square&logo=Python&logoColor=white"/>
                </div>
              </td>
            </tr>
          </table>
        </div>
      </div>

  - title: Project
    layout: list
    content:
      - layout: top-middle
        quote: >
          ì§€ê¸ˆê¹Œì§€ì˜ í”„ë¡œì íŠ¸ ì¤‘ Front-Endì™€ ê´€ë ¨ëœ ì£¼ìš” í”„ë¡œì íŠ¸ ì…ë‹ˆë‹¤.
      - layout: left
        sub_title: ìœ¡ì•„ì˜ ì‹  App ì›¹ë·° ê°œë°œ<br />
        caption: (ì£¼)ì›ë”í’€í”Œë«í¼<br />2020.12 ~ í˜„ì¬
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title: Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title: Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #############ìœ¡ì•„ì˜ì‹  Pdf íŒŒì¼ë“¤ ë³´ë©´ì„œ ì ìœ¼ë©´ ë ë“¯!!!!!!!!!!!!!!!!!
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ê°œìš”

          <strong>â ì—­í• </strong>
            - ~ ìœ¡ì•„ì˜ ì‹  App ì»¤ë®¤ë‹ˆí‹° ì›¹ë·° Front-End ê°œë°œ
            - Zeplinì„ ë°”íƒ•ìœ¼ë¡œ ë””ìì´ë„ˆì™€ ì†Œí†µì„ í†µí•œ UX ë””ìì¸ ì°¸ì—¬
            - Nginx ~
            - ìœ¡ì•„ì˜ ì‹  App ì»¤ë®¤ë‹ˆí‹° ì›¹ë·° Front-End ë¹Œë“œ ë° ë°°í¬
            - ìœ¡ì•„ì˜ ì‹  App ì»¤ë®¤ë‹ˆí‹° ì´ˆê¸° ë‹¨ê³„ë¶€í„° ì„¤ê³„ ë° ê°œë°œ

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - <img src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"/>
            <img src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"/>
            <img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=black"/>
            - <img src="https://img.shields.io/badge/React%20Hooks-61DAFB?style=flat-square&logo=React&logoColor=black"/>
            <img src="https://img.shields.io/badge/React%20Router-CA4245?style=flat-square&logo=React-Router&logoColor=white"/>
            - <img src="https://img.shields.io/badge/styled%20components-DB7093?style=flat-square&logo=styled-components&logoColor=white"/>
            <img src="https://img.shields.io/badge/Material%20UI-0081CB?style=flat-square&logo=Material-UI&logoColor=white"/>
            - <img src="https://img.shields.io/badge/Node.js-339933?style=flat-square&logo=Node.js&logoColor=white"/>
            <img src="https://img.shields.io/badge/Express-000000?style=flat-square&logo=Express&logoColor=white"/>
            <img src="https://img.shields.io/badge/NGINX-009639?style=flat-square&logo=nginx&logoColor=white"/>
            - <img src="https://img.shields.io/badge/ESLint-4B32C3?style=flat-square&logo=ESLint&logoColor=white"/>
            <img src="https://img.shields.io/badge/Prettier-F7B93E?style=flat-square&logo=Prettier&logoColor=white"/>

      - layout: left
        sub_title: AVAdin Works App ì›¹ë·° ê°œë°œ<br />
        caption: (ì£¼)ì›ë”í’€í”Œë«í¼<br />2020.12 ~ í˜„ì¬
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ê°œìš”

          <strong>â ì—­í• </strong>
            - ~ AVAdin Works App ì›¹ë·° Front-End ê°œë°œ
            - Zeplinì„ ë°”íƒ•ìœ¼ë¡œ ë””ìì´ë„ˆì™€ ì†Œí†µì„ í†µí•œ UX ë””ìì¸ ì°¸ì—¬
            - Nginx ~
            - AVAdin Works App ê´€ë¦¬ì í˜ì´ì§€, íŒ€ ì„¸ë¶€ í˜ì´ì§€, ê·¼ë¬´ì¹´ë“œ ì‘ì„± í˜ì´ì§€ ì›¹ë·° Front-End ë¹Œë“œ ë° ë°°í¬

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - <img src="https://img.shields.io/badge/Git-F05032?style=flat-square&logo=Git&logoColor=white"/>
            <img src="https://img.shields.io/badge/npm-CB3837?style=flat-square&logo=npm&logoColor=white"/>
            <img src="https://img.shields.io/badge/Docker-2496ED?style=flat-square&logo=Docker&logoColor=white"/>
            <img src="https://img.shields.io/badge/NGINX-009639?style=flat-square&logo=nginx&logoColor=white"/>
            - <img src="https://img.shields.io/badge/Amazon%20AWS-232F3E?style=flat-square&logo=Amazon%20AWS&logoColor=white"/>
            - <img src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"/>
            <img src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"/>
            <img src="https://img.shields.io/badge/ESLint%20AirBnB-4B32C3?style=flat-square&logo=ESLint&logoColor=white"/>
            - <img src="https://img.shields.io/badge/Swagger-85EA2D?style=flat-square&logo=Swagger&logoColor=white"/>
            <img src="https://img.shields.io/badge/MySQL-4479A1?style=flat-square&logo=MySQL&logoColor=white"/>
            - <img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=black"/>
            <img src="https://img.shields.io/badge/jQuery-0769AD?style=flat-square&logo=jQuery&logoColor=white"/>

  - title: Experience
    layout: list
    content:
      - layout: left
        sub_title: Hi Vacation
        caption: ì†”ë°ìŠ¤í¬ IT ì•„ì¹´ë°ë¯¸<br />2019.01 ~ 2019.04
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ì—¬í–‰ ê³„íšì„ ì„¸ìš°ëŠ” ê³¼ì •ì—ì„œ ìˆ™ë°•, ìŒì‹ì  ë“±ì„ ì„ íƒí•˜ëŠ”ë° ë¶ˆí¸í•¨ì„ í•´ì†Œí•˜ê¸° ìœ„í•œ ì›¹ í”„ë¡œê·¸ë¨
            - ì—¬í–‰ ë™ì„ ì„ ê³„íší•˜ëŠ”ë° í¸ë¦¬í•œ ê¸°ëŠ¥ ì œê³µ

          <strong>â ì—­í• </strong>
            - ì›¹ í˜ì´ì§€ ë””ìì¸
            - Google Maps APIë¥¼ ì ìš©í•´ ì—¬í–‰ ì¼ì •ì„ ê³„íší•˜ëŠ” ê¸°ëŠ¥ êµ¬í˜„
              - ì›í•˜ëŠ” í‚¤ì›Œë“œë¡œ ì¥ì†Œ ê²€ìƒ‰
              - ì°œ ê¸°ëŠ¥
              - ì¼ì • ì €ì¥ (ìº˜ë¦°ë”, My Pageì—ì„œ í™•ì¸ ê°€ëŠ¥)
              - ì˜ˆì‚° ê³„íš

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - <img src="https://img.shields.io/badge/Java-007396?style=flat-square&logo=Java&logoColor=white"/>
            <img src="https://img.shields.io/badge/JSP-333333?style=flat-square&logo=JSP&logoColor=white"/>
            <img src="https://img.shields.io/badge/Spring-6DB33F?style=flat-square&logo=Spring&logoColor=white"/>
            <img src="https://img.shields.io/badge/MyBatis-333333?style=flat-square&logo=MyBatis&logoColor=white"/>
            <img src="https://img.shields.io/badge/Maven-C71A36?style=flat-square&logo=Apache%20Maven&logoColor=white"/>
            <img src="https://img.shields.io/badge/Oracle-F80000?style=flat-square&logo=Oracle&logoColor=white"/>
            - <img src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"/>
            <img src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"/>
            <img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=black"/>
            <img src="https://img.shields.io/badge/jQuery-0769AD?style=flat-square&logo=jQuery&logoColor=white"/>

  - title: About Me
    layout: list
    content:
      - layout: left
        sub_title: ì†Œì œëª©
        description: |
          ìê¸°ì†Œê°œì„œ ì‘ì„±

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
  ]
